# Generated by Django 5.1.7 on 2025-05-20 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barber', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='barber',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barber_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='barber.barber'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='barber.barber'),
        ),
        migrations.AddField(
            model_name='barberservice',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='barber.barber'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='barber_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='barber.barberservice'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_barbershops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='barber',
            name='barbershop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barbers', to='barber.barbershop'),
        ),
        migrations.AddField(
            model_name='barbershopservice',
            name='barbershop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='barber.barbershop'),
        ),
        migrations.AddField(
            model_name='barberservice',
            name='barbershop_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barber_services', to='barber.barbershopservice'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='barber.appointment'),
        ),
        migrations.AddField(
            model_name='barbershopservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barbershop_services', to='barber.service'),
        ),
        migrations.AddField(
            model_name='barberservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_services', to='barber.service'),
        ),
        migrations.AddField(
            model_name='workpost',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_posts', to='barber.barber'),
        ),
        migrations.AddField(
            model_name='workpost',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_posts', to='barber.service'),
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='barber.workpost'),
        ),
        migrations.AlterUniqueTogether(
            name='barbershopservice',
            unique_together={('barbershop', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='barberservice',
            unique_together={('barber', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
    ]
