# Generated by Django 5.1.7 on 2025-05-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0003_city_state_alter_barbershop_city_city_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workpost',
            name='service',
        ),
        migrations.AddField(
            model_name='workpost',
            name='service',
            field=models.ManyToManyField(related_name='work_posts', to='barber.service'),
        ),
    ]
