# Generated by Django 5.1.7 on 2025-05-22 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0004_remove_workpost_service_workpost_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='barbershop',
            name='postal_code',
        ),
    ]
