# Generated by Django 5.1.7 on 2025-05-26 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0005_remove_barber_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barbers_city', to='barber.city'),
        ),
        migrations.AddField(
            model_name='barber',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barbers_state', to='barber.state'),
        ),
    ]
